### ISSUE TITLE
Timer not starting in example code

### ISSUE THREAD

**Issue by vonsivers** [nilsauf/Esp8266PwmShiftRegister#3]
Hello, 
when running the example `shiftRegister.Start()` always returns **false**.
I also tried passing an argument to the function with values between 1...1000 but this did not change anything.
Any help is appreciated.

Board: WEMOS D1 mini ESP8266
Platform IO Core 5.2.4

**Comment by nilsauf** [comment]
Hi @vonsivers,

sorry for only getting back to you now! Thanks for opening the issue.
I fixed the error in my tests. Please test against your code! I will close the issue after your go.

get back if you have more questions :)
